/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.44
 * Generated at: 2017-08-04 01:11:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.semi;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class menubar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("   \r\n");
      out.write("<style>\r\n");
      out.write("form {\r\n");
      out.write("\tpadding : 0px;\r\n");
      out.write("}\r\n");
      out.write("body {\r\n");
      out.write("\ttext-align: right;\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("img {\r\n");
      out.write("\ttransition:1s;\r\n");
      out.write(" \ttransition-timing-function:ease-in-out;\r\n");
      out.write("}\r\n");
      out.write(" img:hover {\r\n");
      out.write("\tmargin-right: 50px;\r\n");
      out.write("\twidth:50px;\r\n");
      out.write("\tbackground:url(\"../image/programmer (1).png\");\r\n");
      out.write("\twidth:50px;\r\n");
      out.write("} \r\n");
      out.write("ul, li {\r\n");
      out.write("\tdisplay:inline-block;\r\n");
      out.write("\tmargin-bottom:30px;\r\n");
      out.write("}\r\n");
      out.write("button {\r\n");
      out.write("\tfont-size:18px;\r\n");
      out.write("\twidth:150px;\r\n");
      out.write("\theight:50px; \r\n");
      out.write(" \tmargin:15px auto; \r\n");
      out.write("\tborder:0px;\r\n");
      out.write("\tbackground-color: Transparent;\r\n");
      out.write("}\r\n");
      out.write("button:hover {\r\n");
      out.write(" \t\t background-color:#F7CA18;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function liveChatOpen(){\r\n");
      out.write("\t");
if(session.getAttribute("id") == null){
      out.write(" //로그인 되어 있지않은경우\r\n");
      out.write("\talert('로그인이 필요한 서비스입니다.');\r\n");
      out.write("\tlocation.href = './login.com'; //로그인창으로 이동\r\n");
      out.write("\treturn false;\r\n");
      out.write("\t");
}
      out.write("\r\n");
      out.write("\twindow.name = \"parentForm\";  \r\n");
      out.write("\twindow.open(\"chatting/ChatLogin\",//url\r\n");
      out.write("\t          \"LiveChatRoom\", \"width=570, height=350, resizable = no, scrollbars = yes\");\r\n");
      out.write("};\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<ul>\r\n");
      out.write("\t<li><button name=\"Recruit\" value=\"Recruit\" class=\"btn btn-sm animated-button recruit\"\r\n");
      out.write("\tonclick=\"location.href='./RecruitList.bo'\">Recruit</button></li>\r\n");
      out.write("\r\n");
      out.write("\t<li><button name=\"Review\" value=\"Review\" class=\"btn btn-sm animated-button review\"\r\n");
      out.write("\t\tonclick=\"location.href='./rvBoardList.bo'\">Review</button></li>\r\n");
      out.write("\t<li><button name=\"source_board\" value=\"source_board\" class=\"btn btn-sm animated-button source\"\r\n");
      out.write("\t\tonclick=\"location.href='./sbBoardList.bo'\">Source Board</button></li>\r\n");
      out.write("\t<li><button name=\"event\" value=\"event\" class=\"btn btn-sm animated-button event\"\r\n");
      out.write("\t\tonclick=\"location.href='./eventBoard.bo'\">Event</button></li>\r\n");
      out.write("\t<li><button name=\"chat\" value=\"chat\" class=\"btn btn-sm animated-button chat\"\r\n");
      out.write("\t\tonclick=\"liveChatOpen()\">Chat</button></li>\r\n");
      out.write("</ul>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
