/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.45
 * Generated at: 2017-09-28 00:17:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.qna;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class qna_005freply_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>REVIEW 답변</title>\r\n");
      out.write("<script src=\"./resources/js/jquery.js\"></script>\r\n");
      out.write("<script src=\"./resources/js/qa2_4.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write(".qaedit_title{font-size: 30pt; font-weight: bold;}\r\n");
      out.write("#qaedit_t{margin-top:10%}\r\n");
      out.write("th {\r\n");
      out.write("\tborder: 2px solid lightgray;\r\n");
      out.write("\twidth: 100px;\r\n");
      out.write("\theight: 50px;\r\n");
      out.write("\tbackground-color: #2ABCB4;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td {\r\n");
      out.write("\tborder: 2px solid lightgray;\r\n");
      out.write("\twidth: 510px;\r\n");
      out.write("\theight: 50px;\r\n");
      out.write("}\r\n");
      out.write(".qaedit_pass,.qaedit_name,.qaedit_subject{width:550px;height: 50px;}\r\n");
      out.write(".qaedit_text,.qaedit_td{    width:660px;\r\n");
      out.write("\theight: 300px;}\r\n");
      out.write("\r\n");
      out.write(".qnareply_bt{    \r\n");
      out.write("    width: 100px;\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("\tbackground: #2ABCB4;\r\n");
      out.write("\tborder: 0px;}\r\n");
      out.write("\t\r\n");
      out.write(".qnareply_back{\twidth: 100px;\r\n");
      out.write("\theight: 30px; \r\n");
      out.write("\tbackground: lightgray;\r\n");
      out.write("\tborder: 0px;}\t\r\n");
      out.write(".qnafilediv{margin-top:-5%}\r\n");
      out.write("#qawrite_menu{margin-top:5%; margin-left:36%}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <div id=\"qawrite_wrap\">\r\n");
      out.write("  <h2 class=\"qaedit_title\">REVIEW 답변</h2>\r\n");
      out.write("  <form method=\"post\" action=\"qna_reply_ok.nhn\" \r\n");
      out.write("  onsubmit=\"return check()\">\r\n");
      out.write("  <input type=\"hidden\" name=\"qna_num\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${qnabean.qna_num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("  <input type=\"hidden\" name=\"login_email\" id=\"login_email\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login_email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("  <input type=\"hidden\" name=\"qna_re_ref\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${qnabean.qna_re_ref}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("  <input type=\"hidden\" name=\"qna_re_lev\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${qnabean.qna_re_lev}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("  <input type=\"hidden\" name=\"qna_re_seq\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${qnabean.qna_re_seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("  <input type=\"hidden\" name=\"page\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("  \r\n");
      out.write("  <table id=\"qawrite_t\">\r\n");
      out.write("    <tr>\r\n");
      out.write("     <th>글쓴이</th>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<label>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login_email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</label>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t <input type=\"hidden\" name=\"qna_name\" id=\"qna_name\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${qnabean.qna_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/> \r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    \r\n");
      out.write("    <tr>\r\n");
      out.write("     <th>비밀번호</th>\r\n");
      out.write("     <td>\r\n");
      out.write("      <input type=\"password\" name=\"qna_pass\" id=\"qna_pass\" size=\"14\"\r\n");
      out.write("      class=\"qaedit_name\" />\r\n");
      out.write("     </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    \r\n");
      out.write("    <tr>\r\n");
      out.write("     <th>제목</th>\r\n");
      out.write("     <td>\r\n");
      out.write("      <input name=\"qna_subject\" id=\"qna_subject\" size=\"40\" \r\n");
      out.write("      class=\"qaedit_subject\" value=\"Re:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${qnabean.qna_subject}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("     </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    \r\n");
      out.write("    <tr>\r\n");
      out.write("  \r\n");
      out.write("     <td colspan=\"2\" class=\"qaedit_td\">\r\n");
      out.write("      <textarea name=\"qna_content\" id=\"qna_content\" rows=\"8\" cols=\"50\"\r\n");
      out.write("      class=\"qaedit_text\"></textarea>\r\n");
      out.write("     </td>\r\n");
      out.write("    </tr>    \r\n");
      out.write("   </table>\r\n");
      out.write("   \r\n");
      out.write("   <div id=\"qawrite_menu\">\r\n");
      out.write("    <input type=\"submit\" value=\"답변\" class=\"qnareply_bt\" />\r\n");
      out.write("    <input type=\"reset\" value=\"취소\" class=\"qnareply_back\"\r\n");
      out.write("    onclick=\"self.close();\" />\r\n");
      out.write("   </div>\r\n");
      out.write("  </form>\r\n");
      out.write(" </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
