/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.44
 * Generated at: 2017-08-03 15:05:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.semi.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import semi.db.*;

public final class MainForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("semi.db");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--첫 메인 페이지 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("euc-kr");

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>JOBS - main</title>\r\n");
      out.write("<link href=\"./css/top.css\" type=\"text/css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"./css/main.css\" type=\"text/css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function () {\r\n");
      out.write("    $(\"ul[data-liffect] li\").each(function (i) {\r\n");
      out.write("        $(this).attr(\"style\", \"-webkit-animation-delay:\" + i * 300 + \"ms;\"\r\n");
      out.write("                + \"-moz-animation-delay:\" + i * 300 + \"ms;\"\r\n");
      out.write("                + \"-o-animation-delay:\" + i * 300 + \"ms;\"\r\n");
      out.write("                + \"animation-delay:\" + i * 300 + \"ms;\");\r\n");
      out.write("        if (i == $(\"ul[data-liffect] li\").size() -1) {\r\n");
      out.write("            $(\"ul[data-liffect]\").addClass(\"play\")\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function liveChatOpen(){\r\n");
      out.write("\t");
if(session.getAttribute("id") == null){
      out.write("\r\n");
      out.write("\talert('로그인이 필요한 서비스입니다.');\r\n");
      out.write("\tlocation.href = './login.com';\r\n");
      out.write("\treturn false;\r\n");
      out.write("\t");
}
      out.write("\r\n");
      out.write("\twindow.name = \"parentForm\"; \r\n");
      out.write("\twindow.open(\"chatting/ChatLogin\",\r\n");
      out.write("\t          \"LiveChatRoom\", \"width=570, height=350, resizable = no, scrollbars = yes\");\r\n");
      out.write("};\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../Header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("    <div class=\"col-md-12 text-center\">\r\n");
      out.write("\t\t\t<img src=\"image/logo.png\">\r\n");
      out.write("\t\t\t<h1 class=\"mrng-60-top\">Jobs</h1> \r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"main_button\">\r\n");
      out.write(" <ul data-liffect=\"bounceIn\">\r\n");
      out.write("<li><button name=\"Recruit\" value=\"Recruit\" class=\"btn btn-sm animated-button recruit\"\r\n");
      out.write("\tonclick=\"location.href='./RecruitList.bo'\">Recruit</button></li>\r\n");
      out.write("\r\n");
  String id = (String)session.getAttribute("id");
	String isE = (String)session.getAttribute("isE");
	if(id != null && id.length() != 0){ 
		if(id.equals("admin")) {
	
      out.write("\r\n");
      out.write("\t<li><button name=\"mypage\" value=\"관리자페이지\" class=\"btn btn-sm animated-button mypage\"\r\n");
      out.write("\tonclick=\"location.href='./adminMemberList.com'\">AdminPage</button></li>\r\n");
      out.write("\t");
}else if(isE != null && isE.length() != 0){ 
      out.write("\r\n");
      out.write("\t<li><button name=\"mypage\" value=\"MYPAGE\" class=\"btn btn-sm animated-button mypage\"\r\n");
      out.write("\tonclick=\"location.href='./EMyPage.com'\">MyPage</button></li>\r\n");
      out.write("\t");
}else { 
      out.write("\r\n");
      out.write("\t<li><button name=\"mypage\" value=\"MYPAGE\" class=\"btn btn-sm animated-button mypage\"\r\n");
      out.write("\tonclick=\"location.href='./PMyPage.com'\">MyPage</button></li>\r\n");
      out.write("\t");
}} else {
      out.write("\r\n");
      out.write("<li><button name=\"login_join\" value=\"Login&Join\" class=\"btn btn-sm animated-button login\"\r\n");
      out.write("\tonclick=\"location.href='./login.com'\">Login</button></li> ");
} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<li><button name=\"Review\" value=\"Review\" class=\"btn btn-sm animated-button review\"\r\n");
      out.write("\tonclick=\"location.href='./rvBoardList.bo'\">Review</button></li>\r\n");
      out.write("<li><button name=\"source_board\" value=\"source_board\" class=\"btn btn-sm animated-button source\"\r\n");
      out.write("\tonclick=\"location.href='./sbBoardList.bo'\">Source Board</button></li>\r\n");
      out.write("<li><button name=\"event\" value=\"event\" class=\"btn btn-sm animated-button event\"\r\n");
      out.write("\tonclick=\"location.href='./eventBoard.bo'\">Event</button></li>\r\n");
      out.write("<li><button name=\"chat\" value=\"chat\" class=\"btn btn-sm animated-button chat\"\r\n");
      out.write("\tonclick=\"liveChatOpen()\">Chat</button></li>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "swiper.jsp", out, false);
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../Footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
