/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.45
 * Generated at: 2017-08-08 05:32:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ch13_005fjstl._005f4_xml;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class jstl_005fxml_005fex_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.1.jar", Long.valueOf(1502071230694L));
    _jspx_dependants.put("jar:file:/I:/KH정보교육원/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/JspProject/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.1.jar!/META-INF/x.tld", Long.valueOf(1323225978000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fx_005fparse_0026_005fvar;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fx_005fforEach_0026_005fselect;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fx_005fif_0026_005fselect;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fx_005fset_0026_005fvar_005fselect_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fx_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fx_005fwhen_0026_005fselect;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fx_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fx_005fparse_0026_005fvar = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fx_005fforEach_0026_005fselect = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fx_005fif_0026_005fselect = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fx_005fset_0026_005fvar_005fselect_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fx_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fx_005fwhen_0026_005fselect = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fx_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fx_005fparse_0026_005fvar.release();
    _005fjspx_005ftagPool_005fx_005fforEach_0026_005fselect.release();
    _005fjspx_005ftagPool_005fx_005fif_0026_005fselect.release();
    _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.release();
    _005fjspx_005ftagPool_005fx_005fset_0026_005fvar_005fselect_005fnobody.release();
    _005fjspx_005ftagPool_005fx_005fchoose.release();
    _005fjspx_005ftagPool_005fx_005fwhen_0026_005fselect.release();
    _005fjspx_005ftagPool_005fx_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!-- JSTL xml은 xml문서에서 자주 사용되는 기능들을 태그 라이브러리로 모아 놓은 것입니다. -->\r\n");
      out.write("<!-- JSTL xml라이브러리를 사용하기 위해 uri 속성과 prefix 속성을 설정합니다. -->\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title>JSTL xml 라이브러리 사용 예제(jstl_xml_ex.jsp)</title>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<!-- XML 데이터를 파싱(특정문서를 읽어 들여서 이를 다른 프로그램이나 서부루틴이 사용할 수 있는\r\n");
      out.write("\t\t\t내부의 표현 방식으로 변환시켜 주는 것)하기 위한 코드입니다.\r\n");
      out.write("\t\t\tx:parse태그 사이에 있는 XMl 내용을 파싱하여 xmldata 변수에 저장합니다. -->\r\n");
      out.write("\t\t");
      if (_jspx_meth_x_005fparse_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- xmldata 변수에 있는 XML 문서의 모든 student엘리먼트를 차례대로 선택해서\r\n");
      out.write("\t\t\t  반복합니다. -->\r\n");
      out.write("\t\t");
      if (_jspx_meth_x_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_x_005fparse_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:parse
    org.apache.taglibs.standard.tag.rt.xml.ParseTag _jspx_th_x_005fparse_005f0 = (org.apache.taglibs.standard.tag.rt.xml.ParseTag) _005fjspx_005ftagPool_005fx_005fparse_0026_005fvar.get(org.apache.taglibs.standard.tag.rt.xml.ParseTag.class);
    boolean _jspx_th_x_005fparse_005f0_reused = false;
    try {
      _jspx_th_x_005fparse_005f0.setPageContext(_jspx_page_context);
      _jspx_th_x_005fparse_005f0.setParent(null);
      // /ch13_jstl/_4.xml/jstl_xml_ex.jsp(15,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005fparse_005f0.setVar("xmldata");
      int _jspx_eval_x_005fparse_005f0 = _jspx_th_x_005fparse_005f0.doStartTag();
      if (_jspx_eval_x_005fparse_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_x_005fparse_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_x_005fparse_005f0);
        }
        do {
          out.write("\r\n");
          out.write("\t\t<students>");
          out.write("\r\n");
          out.write("\t\t\t<student>\r\n");
          out.write("\t\t\t\t<name>홍길동</name>\r\n");
          out.write("\t\t\t\t<age>18</age>\r\n");
          out.write("\t\t\t\t<gender>남</gender>\r\n");
          out.write("\t\t\t\t<phone>010-4567-11xx</phone>\r\n");
          out.write("\t\t\t</student>\r\n");
          out.write("\t\t\t<student>\r\n");
          out.write("\t\t\t\t<name>김길동</name>\r\n");
          out.write("\t\t\t\t<age>19</age>\r\n");
          out.write("\t\t\t\t<gender>남</gender>\r\n");
          out.write("\t\t\t\t<phone>010-4567-00xx</phone>\r\n");
          out.write("\t\t\t</student>\r\n");
          out.write("\t\t\t<student>\r\n");
          out.write("\t\t\t\t<name>홍길순</name>\r\n");
          out.write("\t\t\t\t<age>18</age>\r\n");
          out.write("\t\t\t\t<gender>여</gender>\r\n");
          out.write("\t\t\t\t<phone>없음</phone>\r\n");
          out.write("\t\t\t</student>\r\n");
          out.write("\t\t\t<student>\r\n");
          out.write("\t\t\t\t<name>김길순</name>\r\n");
          out.write("\t\t\t\t<age>18</age>\r\n");
          out.write("\t\t\t\t<gender>여</gender>\r\n");
          out.write("\t\t\t\t<phone>없음</phone>\r\n");
          out.write("\t\t\t</student>\r\n");
          out.write("\t\t</students>\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_x_005fparse_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_x_005fparse_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_x_005fparse_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fx_005fparse_0026_005fvar.reuse(_jspx_th_x_005fparse_005f0);
      _jspx_th_x_005fparse_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_x_005fparse_005f0, _jsp_getInstanceManager(), _jspx_th_x_005fparse_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_x_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:forEach
    org.apache.taglibs.standard.tag.common.xml.ForEachTag _jspx_th_x_005fforEach_005f0 = (org.apache.taglibs.standard.tag.common.xml.ForEachTag) _005fjspx_005ftagPool_005fx_005fforEach_0026_005fselect.get(org.apache.taglibs.standard.tag.common.xml.ForEachTag.class);
    boolean _jspx_th_x_005fforEach_005f0_reused = false;
    try {
      _jspx_th_x_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_x_005fforEach_005f0.setParent(null);
      // /ch13_jstl/_4.xml/jstl_xml_ex.jsp(46,2) name = select type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005fforEach_005f0.setSelect("$xmldata//student");
      int[] _jspx_push_body_count_x_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_x_005fforEach_005f0 = _jspx_th_x_005fforEach_005f0.doStartTag();
        if (_jspx_eval_x_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t");
            if (_jspx_meth_x_005fif_005f0(_jspx_th_x_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_x_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("\t\t");
            int evalDoAfterBody = _jspx_th_x_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_x_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_x_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_x_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_x_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fx_005fforEach_0026_005fselect.reuse(_jspx_th_x_005fforEach_005f0);
      _jspx_th_x_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_x_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_x_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_x_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_x_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_x_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:if
    org.apache.taglibs.standard.tag.common.xml.IfTag _jspx_th_x_005fif_005f0 = (org.apache.taglibs.standard.tag.common.xml.IfTag) _005fjspx_005ftagPool_005fx_005fif_0026_005fselect.get(org.apache.taglibs.standard.tag.common.xml.IfTag.class);
    boolean _jspx_th_x_005fif_005f0_reused = false;
    try {
      _jspx_th_x_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_x_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_x_005fforEach_005f0);
      // /ch13_jstl/_4.xml/jstl_xml_ex.jsp(47,3) name = select type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005fif_005f0.setSelect("./name!='홍길순'");
      int _jspx_eval_x_005fif_005f0 = _jspx_th_x_005fif_005f0.doStartTag();
      if (_jspx_eval_x_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" <!-- 이름이 '홍길순'이 아닐경우 -->\r\n");
          out.write("\t\t\t\t");
          out.write("\r\n");
          out.write("\t\t\t\t");
          if (_jspx_meth_x_005fout_005f0(_jspx_th_x_005fif_005f0, _jspx_page_context, _jspx_push_body_count_x_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\r\n");
          out.write("\t\t\t\t<!-- age엘리먼트의 값을 age변수에 저장합니다. -->\r\n");
          out.write("\t\t\t\t");
          if (_jspx_meth_x_005fset_005f0(_jspx_th_x_005fif_005f0, _jspx_page_context, _jspx_push_body_count_x_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\r\n");
          out.write("\t\t\t\t<!-- age변수 값을 출력합니다. -->\r\n");
          out.write("\t\t\t\t");
          if (_jspx_meth_x_005fout_005f1(_jspx_th_x_005fif_005f0, _jspx_page_context, _jspx_push_body_count_x_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\r\n");
          out.write("\t\t\t\t<!-- gender엘리먼트의 값을 출력합니다. -->\r\n");
          out.write("\t\t\t\t");
          if (_jspx_meth_x_005fout_005f2(_jspx_th_x_005fif_005f0, _jspx_page_context, _jspx_push_body_count_x_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\r\n");
          out.write("\t\t\t\t<!-- 조건문 -->\r\n");
          out.write("\t\t\t\t");
          if (_jspx_meth_x_005fchoose_005f0(_jspx_th_x_005fif_005f0, _jspx_page_context, _jspx_push_body_count_x_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t<br>\r\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_x_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_x_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fx_005fif_0026_005fselect.reuse(_jspx_th_x_005fif_005f0);
      _jspx_th_x_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_x_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_x_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_x_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_x_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_x_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:out
    org.apache.taglibs.standard.tag.rt.xml.ExprTag _jspx_th_x_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.xml.ExprTag) _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.get(org.apache.taglibs.standard.tag.rt.xml.ExprTag.class);
    boolean _jspx_th_x_005fout_005f0_reused = false;
    try {
      _jspx_th_x_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_x_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_x_005fif_005f0);
      // /ch13_jstl/_4.xml/jstl_xml_ex.jsp(53,4) name = select type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005fout_005f0.setSelect("./name");
      int _jspx_eval_x_005fout_005f0 = _jspx_th_x_005fout_005f0.doStartTag();
      if (_jspx_th_x_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.reuse(_jspx_th_x_005fout_005f0);
      _jspx_th_x_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_x_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_x_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_x_005fset_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_x_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_x_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:set
    org.apache.taglibs.standard.tag.common.xml.SetTag _jspx_th_x_005fset_005f0 = (org.apache.taglibs.standard.tag.common.xml.SetTag) _005fjspx_005ftagPool_005fx_005fset_0026_005fvar_005fselect_005fnobody.get(org.apache.taglibs.standard.tag.common.xml.SetTag.class);
    boolean _jspx_th_x_005fset_005f0_reused = false;
    try {
      _jspx_th_x_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_x_005fset_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_x_005fif_005f0);
      // /ch13_jstl/_4.xml/jstl_xml_ex.jsp(56,4) name = select type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005fset_005f0.setSelect("./age");
      // /ch13_jstl/_4.xml/jstl_xml_ex.jsp(56,4) name = var type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005fset_005f0.setVar("age");
      int _jspx_eval_x_005fset_005f0 = _jspx_th_x_005fset_005f0.doStartTag();
      if (_jspx_th_x_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fx_005fset_0026_005fvar_005fselect_005fnobody.reuse(_jspx_th_x_005fset_005f0);
      _jspx_th_x_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_x_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_x_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_x_005fout_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_x_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_x_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:out
    org.apache.taglibs.standard.tag.rt.xml.ExprTag _jspx_th_x_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.xml.ExprTag) _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.get(org.apache.taglibs.standard.tag.rt.xml.ExprTag.class);
    boolean _jspx_th_x_005fout_005f1_reused = false;
    try {
      _jspx_th_x_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_x_005fout_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_x_005fif_005f0);
      // /ch13_jstl/_4.xml/jstl_xml_ex.jsp(59,4) name = select type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005fout_005f1.setSelect("$age");
      int _jspx_eval_x_005fout_005f1 = _jspx_th_x_005fout_005f1.doStartTag();
      if (_jspx_th_x_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.reuse(_jspx_th_x_005fout_005f1);
      _jspx_th_x_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_x_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_x_005fout_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_x_005fout_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_x_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_x_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:out
    org.apache.taglibs.standard.tag.rt.xml.ExprTag _jspx_th_x_005fout_005f2 = (org.apache.taglibs.standard.tag.rt.xml.ExprTag) _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.get(org.apache.taglibs.standard.tag.rt.xml.ExprTag.class);
    boolean _jspx_th_x_005fout_005f2_reused = false;
    try {
      _jspx_th_x_005fout_005f2.setPageContext(_jspx_page_context);
      _jspx_th_x_005fout_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_x_005fif_005f0);
      // /ch13_jstl/_4.xml/jstl_xml_ex.jsp(62,4) name = select type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005fout_005f2.setSelect("./gender");
      int _jspx_eval_x_005fout_005f2 = _jspx_th_x_005fout_005f2.doStartTag();
      if (_jspx_th_x_005fout_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.reuse(_jspx_th_x_005fout_005f2);
      _jspx_th_x_005fout_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_x_005fout_005f2, _jsp_getInstanceManager(), _jspx_th_x_005fout_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_x_005fchoose_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_x_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_x_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_x_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fx_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_x_005fchoose_005f0_reused = false;
    try {
      _jspx_th_x_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_x_005fchoose_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_x_005fif_005f0);
      int _jspx_eval_x_005fchoose_005f0 = _jspx_th_x_005fchoose_005f0.doStartTag();
      if (_jspx_eval_x_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t");
          if (_jspx_meth_x_005fwhen_005f0(_jspx_th_x_005fchoose_005f0, _jspx_page_context, _jspx_push_body_count_x_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t");
          if (_jspx_meth_x_005fotherwise_005f0(_jspx_th_x_005fchoose_005f0, _jspx_page_context, _jspx_push_body_count_x_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_x_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_x_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fx_005fchoose.reuse(_jspx_th_x_005fchoose_005f0);
      _jspx_th_x_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_x_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_x_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_x_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_x_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_x_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:when
    org.apache.taglibs.standard.tag.common.xml.WhenTag _jspx_th_x_005fwhen_005f0 = (org.apache.taglibs.standard.tag.common.xml.WhenTag) _005fjspx_005ftagPool_005fx_005fwhen_0026_005fselect.get(org.apache.taglibs.standard.tag.common.xml.WhenTag.class);
    boolean _jspx_th_x_005fwhen_005f0_reused = false;
    try {
      _jspx_th_x_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_x_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_x_005fchoose_005f0);
      // /ch13_jstl/_4.xml/jstl_xml_ex.jsp(66,5) name = select type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005fwhen_005f0.setSelect("./phone!='없음'");
      int _jspx_eval_x_005fwhen_005f0 = _jspx_th_x_005fwhen_005f0.doStartTag();
      if (_jspx_eval_x_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t[전화번호 : ");
          if (_jspx_meth_x_005fout_005f3(_jspx_th_x_005fwhen_005f0, _jspx_page_context, _jspx_push_body_count_x_005fforEach_005f0))
            return true;
          out.write("]\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_x_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_x_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fx_005fwhen_0026_005fselect.reuse(_jspx_th_x_005fwhen_005f0);
      _jspx_th_x_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_x_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_x_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_x_005fout_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_x_005fwhen_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_x_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:out
    org.apache.taglibs.standard.tag.rt.xml.ExprTag _jspx_th_x_005fout_005f3 = (org.apache.taglibs.standard.tag.rt.xml.ExprTag) _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.get(org.apache.taglibs.standard.tag.rt.xml.ExprTag.class);
    boolean _jspx_th_x_005fout_005f3_reused = false;
    try {
      _jspx_th_x_005fout_005f3.setPageContext(_jspx_page_context);
      _jspx_th_x_005fout_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_x_005fwhen_005f0);
      // /ch13_jstl/_4.xml/jstl_xml_ex.jsp(67,14) name = select type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005fout_005f3.setSelect("./phone");
      int _jspx_eval_x_005fout_005f3 = _jspx_th_x_005fout_005f3.doStartTag();
      if (_jspx_th_x_005fout_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.reuse(_jspx_th_x_005fout_005f3);
      _jspx_th_x_005fout_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_x_005fout_005f3, _jsp_getInstanceManager(), _jspx_th_x_005fout_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_x_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_x_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_x_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_x_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fx_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_x_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_x_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_x_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_x_005fchoose_005f0);
      int _jspx_eval_x_005fotherwise_005f0 = _jspx_th_x_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_x_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t[전화 없음]\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_x_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_x_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fx_005fotherwise.reuse(_jspx_th_x_005fotherwise_005f0);
      _jspx_th_x_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_x_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_x_005fotherwise_005f0_reused);
    }
    return false;
  }
}
