/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.44
 * Generated at: 2017-07-25 06:36:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ch14._005f1_Model2.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import net.board.db.*;

public final class qna_005fboard_005fview_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("net.board.db");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--  글 내용을 보여주는 View 페이지 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");

//게시물의 내용이 담겨있는 boarddata 속성의 데이터를 BoardBean 타입으로 
//변환하여 얻습니다.
  BoardBean board = (BoardBean)request.getAttribute("boarddata");

      out.write("\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<title>MVC 게시판</title>\r\n");
      out.write("\t<link href=\"css/ch14_1.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<!-- 게시판 수정 -->\r\n");
      out.write("<table>\r\n");
      out.write("\t<tr valign=\"middle\">\r\n");
      out.write("\t\t<th colspan=\"2\">MVC 게시판-view페이지</th>\r\n");
      out.write("\t</tr>\t\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<div>글쓴이</div>\r\n");
      out.write("\t\t</td>\t\t\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t");
      out.print(board.getBOARD_NAME());
      out.write("\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\t\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<div>제 목</div>\r\n");
      out.write("\t\t</td>\t\t\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t");
      out.print(board.getBOARD_SUBJECT());
      out.write("<!-- 게시물의 제목을 출력합니다. -->\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\t\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<div>내 용</div>\r\n");
      out.write("\t\t</td>\t\t\r\n");
      out.write("\t\t<td>\t\t\r\n");
      out.write("\t\t <textarea name=\"BOARD_CONTENT\" \r\n");
      out.write("\t\t   cols=\"67\" rows=\"15\">");
      out.print(board.getBOARD_CONTENT() );
      out.write("</textarea>\r\n");
      out.write("\t\t</td>\t\t\t\r\n");
      out.write("\t</tr>\t\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<div>첨부파일</div>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t<!-- 게시물에 첨부파일이 존재할 경우 첨부 파일의 링크를 표시합니다. -->\r\n");
      out.write("\t\t");
if(!(board.getBOARD_FILE()==null)){ 			
		
      out.write("\r\n");
      out.write("\t\t <a href=\"./boardupload/");
      out.print(board.getBOARD_FILE());
      out.write("\" download>\r\n");
      out.write("\t\t\t");
      out.print(board.getBOARD_FILE() );
      out.write("\r\n");
      out.write("\t\t    </a>\r\n");
      out.write("\t    ");
} 
      out.write("\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("\t<tr bgcolor=\"00ffff\">\r\n");
      out.write("\t\t<td colspan=\"2\" style=\"height:1px;\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 답변, 수정, 삭제, 목록의 링크를 표시합니다. -->\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td colspan=\"2\" class=\"h30 lime center\">\r\n");
      out.write("\t\t\t<a href=\"./BoardReplyView.bo?num=");
      out.print(board.getBOARD_NUM() );
      out.write("\">\r\n");
      out.write("\t\t\t[답변]\r\n");
      out.write("\t\t\t</a>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t<a href=\"./BoardModify.bo?num=");
      out.print(board.getBOARD_NUM() );
      out.write("\">\r\n");
      out.write("\t\t\t[수정]\r\n");
      out.write("\t\t\t</a>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t<a href=\"./BoardDelete.bo?num=");
      out.print(board.getBOARD_NUM() );
      out.write("\">\r\n");
      out.write("\t\t\t[삭제]\r\n");
      out.write("\t\t\t</a>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t<a href=\"./BoardList.bo\">[목록]</a>&nbsp;&nbsp;\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
